name: KiXServ
version: 1.0.0
author: cfi2017
main: dev.swiss.kix.Main
api-version: '1.14'
website: https://swiss.dev/
commands:
  kix:
    description: hub command for all kix commands
#  warp:
#    description: warp
#    usage: /warp <warp>
#    permission: kix.warp